### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by georgebrianb** [apurvsinghgautam/HTTP-Reverse-Shell#2]
Hello, this is a very useful tool, but could you add some more documentation?
I am having issues establishing the connection.
More useful info would be - what does the 192.168.158.128 IP stands for
What does the /store path do?
An example of running the two scripts and running any command with the utility!

Thanks for the great job.

**Comment by apurvsinghgautam** [comment]
Sure. I will add more info and screenshots
